# Generated by Django 5.2.1 on 2025-07-24 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_formpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="childrelationship",
            name="parent_submission",
            field=models.ForeignKey(
                limit_choices_to={"parent_submission__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_relationships",
                to="core.formsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="childrelationship",
            name="source_submission",
            field=models.ForeignKey(
                help_text="The 'from' side of the relationship (e.g., a Teacher).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships_as_source",
                to="core.formsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="childrelationship",
            name="target_submission",
            field=models.ForeignKey(
                help_text="The 'to' side of the relationship (e.g., a Student).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships_as_target",
                to="core.formsubmission",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="childrelationship",
            unique_together={
                (
                    "parent_submission",
                    "source_submission",
                    "target_submission",
                    "relationship_type",
                )
            },
        ),
    ]
