# Generated by Django 5.2.4 on 2025-07-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_childrelationship_parent_submission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="form_name",
            field=models.CharField(max_length=255),
        ),
    ]
